
import type {
    Contact,
    MasterIntervention,
    CustomListItem,
    CustomList
  } from "@/types";


export const contactsData: Omit<Contact, 'id'>[] = [
    {
        firstName: 'Γιώργος',
        lastName: 'Τεχνικός',
        email: 'g.technikos@example.com',
        mobilePhone: '6971234567',
        landlinePhone: '2810123456',
        role: 'Τεχνίτης',
        specialty: 'Ηλεκτρολόγος Μηχανικός',
        company: 'Τεχνικές Λύσεις Α.Ε.',
        addressStreet: 'Δαιδάλου',
        addressNumber: '12',
        addressCity: 'Ηράκλειο',
        addressPostalCode: '71202',
        addressPrefecture: 'Ηρακλείου',
        avatar: 'https://i.pravatar.cc/150?u=contact-1',
        notes: 'Εξειδικευμένος σε συστήματα smart home.',
    },
    {
        firstName: 'Μαρία',
        lastName: 'Προμηθεύτρια',
        email: 'm.promitheutria@materials.com',
        mobilePhone: '6987654321',
        role: 'Προμηθευτής',
        specialty: 'Κουφώματα & Μονωτικά',
        company: 'Alpha Materials',
        addressStreet: 'Βιομηχανική Περιοχή Θεσσαλονίκης',
        addressCity: 'Θεσσαλονίκη',
        avatar: 'https://i.pravatar.cc/150?u=contact-2',
        notes: 'Παράδοση εντός 5 εργάσιμων ημερών για κουφώματα.',
    },
    {
        firstName: 'Νίκος',
        lastName: 'Λογιστής',
        email: 'nikos.logistis@accountants.gr',
        landlinePhone: '2101234567',
        role: 'Λογιστήριο',
        specialty: 'Φοροτεχνικός',
        company: 'Λογιστικές Υπηρεσίες Ελλάδος',
        addressStreet: 'Σταδίου',
        addressNumber: '50',
        addressCity: 'Αθήνα',
        addressPostalCode: '10564',
        avatar: 'https://i.pravatar.cc/150?u=contact-3',
        notes: 'Υπεύθυνος για τιμολογήσεις έργων.',
    },
     {
        firstName: 'Ιωάννης',
        lastName: 'Παπαδόπουλος',
        email: 'ioannis.p@gmail.com',
        mobilePhone: '6944444444',
        role: 'Πελάτης',
        addressStreet: 'Αγίου Γεωργίου',
        addressNumber: '23',
        addressCity: 'Μαρούσι',
        avatar: 'https://i.pravatar.cc/150?u=contact-4',
        notes: 'Ιδιοκτήτης του έργου "Ανακαίνιση Μονοκατοικίας στο Μαρούσι".',
    },
     {
        firstName: 'Μαρία',
        lastName: 'Γεωργίου',
        email: 'maria.g@yahoo.com',
        mobilePhone: '6933333333',
        role: 'Πελάτης',
        addressStreet: 'Αγίας Σοφίας',
        addressNumber: '15',
        addressCity: 'Πάτρα',
        avatar: 'https://i.pravatar.cc/150?u=contact-5',
        notes: 'Ιδιοκτήτρια του έργου "Ενεργειακή Αναβάθμιση Διαμερίσματος στην Πάτρα".',
    },
     {
        firstName: 'Εταιρεία',
        lastName: 'Α.Ε.',
        email: 'info@etaireia.gr',
        landlinePhone: '2109876543',
        role: 'Πελάτης',
        company: 'Hellenic Business Corp.',
        addressStreet: 'Λεωφόρος Συγγρού',
        addressNumber: '100',
        addressCity: 'Αθήνα',
        avatar: 'https://placehold.co/40x40.png',
        notes: 'Ιδιοκτήτης του έργου "Εγκατάσταση Φ/Β σε Επαγγελματικό Χώρο".',
    },
     {
        firstName: 'Κώστας',
        lastName: 'Μάστορας',
        email: 'k.mastoras@workers.com',
        mobilePhone: '6911111111',
        role: 'Τεχνίτης',
        specialty: 'Υδραυλικός/Εγκαταστάτης Θέρμανσης',
        company: 'ΑΜΕΣΗ ΔΡΑΣΗ',
        addressCity: 'Πάτρα',
        avatar: 'https://i.pravatar.cc/150?u=contact-6',
        notes: 'Ειδικός σε αντλίες θερμότητας.',
    },
];

export const masterInterventionsData: Omit<MasterIntervention, 'id' | 'code'>[] = [
    {
        info: "Κουφώματα – Υαλοπίνακες – Συστήματα Σκίασης",
        expenseCategory: "Κουφώματα",
        interventionCategory: "Κουφώματα",
        interventionSubcategory: "Αντικατάσταση Κουφωμάτων - Πλαίσιο αλουμινίου με θερμοδιακοπή",
        unit: "€/m²",
        maxUnitPrice: 320,
        maxAmount: 10000,
        energySpecsOptions: "U < 1.8",
    },
    {
        info: "Θερμομόνωση",
        expenseCategory: "Θερμομόνωση",
        interventionCategory: "Θερμομόνωση",
        interventionSubcategory: "Εξωτερική Θερμομόνωση (Κέλυφος)",
        unit: "€/m²",
        maxUnitPrice: 65,
        maxAmount: 8000,
        energySpecsOptions: "Πάχος 10cm",
    },
    {
        info: "Συστήματα Θέρμανσης - Ψύξης",
        expenseCategory: "Συστήματα Θέρμανσης-Ψύξης",
        interventionCategory: "Συστήματα Θέρμανσης-Ψύξης",
        interventionSubcategory: "Αντλία Θερμότητας - Αέρος-Νερού για θέρμανση/ψύξη",
        unit: "€/kW",
        maxUnitPrice: 950,
        maxAmount: 12000,
        energySpecsOptions: "8kW < P ≤ 12kW",
    },
    {
        info: "Συστήματα Παροχής Ζεστού Νερού Χρήσης (ΖΝΧ)",
        expenseCategory: "ΖΝΧ",
        interventionCategory: "ΖΝΧ",
        interventionSubcategory: "Ηλιακός θερμοσίφωνας - Επιλεκτικός συλλέκτης κενού",
        unit: "€/μονάδα",
        maxUnitPrice: 1800,
        maxAmount: 2000,
        energySpecsOptions: "200L",
    },
     {
        info: "Λοιπές Παρεμβάσεις Εξοικονόμησης Ενέργειας",
        expenseCategory: "Λοιπές Παρεμβάσεις",
        interventionCategory: "Λοιπές Παρεμβάσεις",
        interventionSubcategory: "Φωτοβολταϊκό Σύστημα - Net metering",
        unit: "€/kW",
        maxUnitPrice: 1300,
        maxAmount: 15000,
    }
];

// Data for custom lists seeding
export const customListsSeedData: Omit<CustomList, 'id'>[] = [
    { name: 'Κωδικός', key: 'CODE' },
    { name: 'Κατηγορία Παρέμβασης', key: 'INTERVENTION_CATEGORY' },
    { name: 'Κατηγορία Δαπάνης', key: 'EXPENSE_CATEGORY' },
    { name: 'Υπο-Κατηγορία Παρέμβασης', key: 'SUB_INTERVENTION_CATEGORY' },
    { name: 'info', key: 'INFO' },
    { name: 'Ενεργειακά Χαρακτηριστικά', key: 'ENERGY_SPECS' },
    { name: 'τίτλοι παρεμβάσεων', key: 'INTERVENTION_TITLES' },
    { name: 'Ρόλοι Επαφών', key: 'CONTACT_ROLES' },
    { name: 'Μονάδες Μέτρησης', key: 'UNIT_OF_MEASUREMENT' },
];

export const customListItemsSeedData: { listKey: string; items: string[] }[] = [
    { listKey: 'CODE', items: ["1.A1", "1.B1", "1.C1", "1.D1", "1.E1", "1.Γ1", "1.Γ2", "1.Ε1"] },
    { listKey: 'INTERVENTION_CATEGORY', items: ["Κουφώματα", "Θερμομόνωση", "Συστήματα Θέρμανσης-Ψύξης", "ΖΝΧ", "Λοιπές Παρεμβάσεις"] },
    { listKey: 'EXPENSE_CATEGORY', items: ["Κουφώματα (I)", "Θερμομόνωση (II)", "Συστήματα Θέρμανσης-Ψύξης (III)", "ΖΝΧ (IV)", "Λοιπές Παρεμβάσεις (V)"] },
    { listKey: 'SUB_INTERVENTION_CATEGORY', items: ["Πλαίσιο PVC με υαλοπίνακα - Παράθυρο (U < 2,0)", "Πλαίσιο PVC με υαλοπίνακα - Εξωστόθυρα (U < 2,0)", "Εξωτερικό προστατευτικό φύλλο (σύστημα Κουτί–Ρολό, ή Εξώφυλλο)"] },
    { listKey: 'INFO', items: ["Κουφώματα – Υαλοπίνακες – Συστήματα Σκίασης", "Θερμομόνωση", "Συστήματα Θέρμανσης - Ψύξης", "Συστήματα Παροχής Ζεστού Νερού Χρήσης (ΖΝΧ)", "Λοιπές Παρεμβάσεις Εξοικονόμησης Ενέργειας"] },
    { listKey: 'ENERGY_SPECS', items: ["U < 1.8", "Πάχος 10cm", "8kW < P ≤ 12kW", "200L"] },
    { listKey: 'INTERVENTION_TITLES', items: ["Αντικατάσταση Κουφωμάτων", "Εξωτερική Θερμομόνωση (Κέλυφος)", "Αντλία Θερμότητας", "Ηλιακός θερμοσίφωνας", "Φωτοβολταϊκό Σύστημα"] },
    { listKey: 'CONTACT_ROLES', items: ["Πελάτης", "Προμηθευτής", "Τεχνίτης", "Λογιστήριο", "Μηχανικός", "Συνεργείο", "Άλλο"] },
    { listKey: 'UNIT_OF_MEASUREMENT', items: ["€/m²", "€/kW", "€/μονάδα", "€/αίτηση", "τεμ.", "m", "m²", "m³", "kW", "kWh"] },
];
